//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.26 at 02:35:15 PM IST 
//


package com.cxmlpunchout.sebo;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}doctype"/>
 *         &lt;element ref="{}salesorg"/>
 *         &lt;element ref="{}username"/>
 *         &lt;element ref="{}password"/>
 *         &lt;element ref="{}custAcctNum"/>
 *         &lt;element ref="{}distchannel"/>
 *         &lt;element ref="{}division"/>
 *         &lt;element ref="{}prtnrole"/>
 *         &lt;element ref="{}prtnnum"/>
 *         &lt;element ref="{}shipto"/>
 *         &lt;element ref="{}setshipto"/>
 *         &lt;element ref="{}plant"/>
 *         &lt;element ref="{}slsoffice"/>
 *         &lt;element ref="{}po"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}phone"/>
 *         &lt;element ref="{}email"/>
 *         &lt;element ref="{}shipprtnr"/>
 *         &lt;element ref="{}curr"/>
 *         &lt;element ref="{}salestype"/>
 *         &lt;element ref="{}shiptype"/>
 *         &lt;element ref="{}freightterm"/>
 *         &lt;element ref="{}freighttermdesc"/>
 *         &lt;element ref="{}shipviaacct"/>
 *         &lt;element ref="{}shipviaid"/>
 *         &lt;element ref="{}shipmethod"/>
 *         &lt;element ref="{}pricecode"/>
 *         &lt;element ref="{}comment"/>
 *         &lt;element ref="{}payment"/>
 *         &lt;element ref="{}paymentdesc"/>
 *         &lt;element ref="{}userid"/>
 *         &lt;element ref="{}total"/>
 *         &lt;element ref="{}statusid"/>
 *         &lt;element ref="{}order-for"/>
 *         &lt;element ref="{}ordertype"/>
 *         &lt;element ref="{}freighttermlevel"/>
 *         &lt;element ref="{}freighttermservicelevel"/>
 *         &lt;element ref="{}parceltermlevel"/>
 *         &lt;element ref="{}parceltermservicelevel"/>
 *         &lt;element ref="{}freightaccount"/>
 *         &lt;element ref="{}ordertypepartnernumber"/>
 *         &lt;element ref="{}shipmethodid"/>
 *         &lt;element ref="{}reqdate"/>
 *         &lt;element ref="{}pterms"/>
 *         &lt;element ref="{}fterms"/>
 *         &lt;element ref="{}prnum"/>
 *         &lt;element ref="{}replytotype"/>
 *         &lt;element ref="{}replyto"/>
 *         &lt;element ref="{}mfrid"/>
 *         &lt;element ref="{}extvendnum"/>
 *         &lt;element ref="{}vendorid"/>
 *         &lt;element ref="{}cctype"/>
 *         &lt;element ref="{}ccnum"/>
 *         &lt;element ref="{}ccname"/>
 *         &lt;element ref="{}ccdate"/>
 *         &lt;element ref="{}seorderid"/>
 *         &lt;element ref="{}reasoncode"/>
 *         &lt;element ref="{}custdbpool"/>
 *         &lt;element ref="{}admindbpool"/>
 *         &lt;element ref="{}secustomerid"/>
 *         &lt;element ref="{}locationID"/>
 *         &lt;element ref="{}seOrderID"/>
 *         &lt;element ref="{}reqstoreid"/>
 *         &lt;element ref="{}ordertypedesc"/>
 *         &lt;element ref="{}paymentTerms"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "doctype",
    "salesorg",
    "username",
    "password",
    "custAcctNum",
    "distchannel",
    "division",
    "prtnrole",
    "prtnnum",
    "shipto",
    "setshipto",
    "plant",
    "slsoffice",
    "po",
    "name",
    "phone",
    "email",
    "shipprtnr",
    "curr",
    "salestype",
    "shiptype",
    "freightterm",
    "freighttermdesc",
    "shipviaacct",
    "shipviaid",
    "shipmethod",
    "pricecode",
    "comment",
    "payment",
    "paymentdesc",
    "userid",
    "total",
    "statusid",
    "orderFor",
    "ordertype",
    "freighttermlevel",
    "freighttermservicelevel",
    "parceltermlevel",
    "parceltermservicelevel",
    "freightaccount",
    "ordertypepartnernumber",
    "shipmethodid",
    "reqdate",
    "pterms",
    "fterms",
    "prnum",
    "replytotype",
    "replyto",
    "mfrid",
    "extvendnum",
    "vendorid",
    "cctype",
    "ccnum",
    "ccname",
    "ccdate",
    "seorderid",
    "reasoncode",
    "custdbpool",
    "admindbpool",
    "secustomerid",
    "locationID",
    "seOrderID",
    "reqstoreid",
    "ordertypedesc",
    "paymentTerms"
})
@XmlRootElement(name = "hdrrec")
public class Hdrrec {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String doctype;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String salesorg;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String username;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String custAcctNum;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String distchannel;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String division;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String prtnrole;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String prtnnum;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String shipto;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String setshipto;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String plant;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String slsoffice;
    @XmlElement(required = true)
    protected BigInteger po;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String phone;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String shipprtnr;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String curr;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String salestype;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String shiptype;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String freightterm;
    @XmlElement(required = true)
    protected String freighttermdesc;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String shipviaacct;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String shipviaid;
    @XmlElement(required = true)
    protected String shipmethod;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pricecode;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String comment;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String payment;
    @XmlElement(required = true)
    protected String paymentdesc;
    @XmlElement(required = true)
    protected BigInteger userid;
    @XmlElement(required = true)
    protected BigDecimal total;
    @XmlElement(required = true)
    protected BigInteger statusid;
    @XmlElement(name = "order-for", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String orderFor;
    @XmlElement(required = true)
    protected BigInteger ordertype;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String freighttermlevel;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String freighttermservicelevel;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String parceltermlevel;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String parceltermservicelevel;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String freightaccount;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ordertypepartnernumber;
    @XmlElement(required = true)
    protected BigInteger shipmethodid;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String reqdate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pterms;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fterms;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String prnum;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String replytotype;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String replyto;
    @XmlElement(required = true)
    protected BigInteger mfrid;
    @XmlElement(required = true)
    protected BigInteger extvendnum;
    @XmlElement(required = true)
    protected BigInteger vendorid;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String cctype;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ccnum;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ccname;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ccdate;
    @XmlElement(required = true)
    protected BigInteger seorderid;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String reasoncode;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String custdbpool;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String admindbpool;
    @XmlElement(required = true)
    protected BigInteger secustomerid;
    @XmlElement(required = true)
    protected BigInteger locationID;
    @XmlElement(required = true)
    protected BigInteger seOrderID;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String reqstoreid;
    @XmlElement(required = true)
    protected String ordertypedesc;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String paymentTerms;

    /**
     * Gets the value of the doctype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoctype() {
        return doctype;
    }

    /**
     * Sets the value of the doctype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoctype(String value) {
        this.doctype = value;
    }

    /**
     * Gets the value of the salesorg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesorg() {
        return salesorg;
    }

    /**
     * Sets the value of the salesorg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesorg(String value) {
        this.salesorg = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the custAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustAcctNum() {
        return custAcctNum;
    }

    /**
     * Sets the value of the custAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustAcctNum(String value) {
        this.custAcctNum = value;
    }

    /**
     * Gets the value of the distchannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistchannel() {
        return distchannel;
    }

    /**
     * Sets the value of the distchannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistchannel(String value) {
        this.distchannel = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivision(String value) {
        this.division = value;
    }

    /**
     * Gets the value of the prtnrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrtnrole() {
        return prtnrole;
    }

    /**
     * Sets the value of the prtnrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrtnrole(String value) {
        this.prtnrole = value;
    }

    /**
     * Gets the value of the prtnnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrtnnum() {
        return prtnnum;
    }

    /**
     * Sets the value of the prtnnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrtnnum(String value) {
        this.prtnnum = value;
    }

    /**
     * Gets the value of the shipto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipto() {
        return shipto;
    }

    /**
     * Sets the value of the shipto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipto(String value) {
        this.shipto = value;
    }

    /**
     * Gets the value of the setshipto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetshipto() {
        return setshipto;
    }

    /**
     * Sets the value of the setshipto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetshipto(String value) {
        this.setshipto = value;
    }

    /**
     * Gets the value of the plant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlant() {
        return plant;
    }

    /**
     * Sets the value of the plant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlant(String value) {
        this.plant = value;
    }

    /**
     * Gets the value of the slsoffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlsoffice() {
        return slsoffice;
    }

    /**
     * Sets the value of the slsoffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlsoffice(String value) {
        this.slsoffice = value;
    }

    /**
     * Gets the value of the po property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPo() {
        return po;
    }

    /**
     * Sets the value of the po property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPo(BigInteger value) {
        this.po = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the shipprtnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipprtnr() {
        return shipprtnr;
    }

    /**
     * Sets the value of the shipprtnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipprtnr(String value) {
        this.shipprtnr = value;
    }

    /**
     * Gets the value of the curr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurr() {
        return curr;
    }

    /**
     * Sets the value of the curr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurr(String value) {
        this.curr = value;
    }

    /**
     * Gets the value of the salestype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalestype() {
        return salestype;
    }

    /**
     * Sets the value of the salestype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalestype(String value) {
        this.salestype = value;
    }

    /**
     * Gets the value of the shiptype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShiptype() {
        return shiptype;
    }

    /**
     * Sets the value of the shiptype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShiptype(String value) {
        this.shiptype = value;
    }

    /**
     * Gets the value of the freightterm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightterm() {
        return freightterm;
    }

    /**
     * Sets the value of the freightterm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightterm(String value) {
        this.freightterm = value;
    }

    /**
     * Gets the value of the freighttermdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreighttermdesc() {
        return freighttermdesc;
    }

    /**
     * Sets the value of the freighttermdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreighttermdesc(String value) {
        this.freighttermdesc = value;
    }

    /**
     * Gets the value of the shipviaacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipviaacct() {
        return shipviaacct;
    }

    /**
     * Sets the value of the shipviaacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipviaacct(String value) {
        this.shipviaacct = value;
    }

    /**
     * Gets the value of the shipviaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipviaid() {
        return shipviaid;
    }

    /**
     * Sets the value of the shipviaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipviaid(String value) {
        this.shipviaid = value;
    }

    /**
     * Gets the value of the shipmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmethod() {
        return shipmethod;
    }

    /**
     * Sets the value of the shipmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmethod(String value) {
        this.shipmethod = value;
    }

    /**
     * Gets the value of the pricecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricecode() {
        return pricecode;
    }

    /**
     * Sets the value of the pricecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricecode(String value) {
        this.pricecode = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayment(String value) {
        this.payment = value;
    }

    /**
     * Gets the value of the paymentdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentdesc() {
        return paymentdesc;
    }

    /**
     * Sets the value of the paymentdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentdesc(String value) {
        this.paymentdesc = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserid() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserid(BigInteger value) {
        this.userid = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotal(BigDecimal value) {
        this.total = value;
    }

    /**
     * Gets the value of the statusid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatusid() {
        return statusid;
    }

    /**
     * Sets the value of the statusid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatusid(BigInteger value) {
        this.statusid = value;
    }

    /**
     * Gets the value of the orderFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderFor() {
        return orderFor;
    }

    /**
     * Sets the value of the orderFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderFor(String value) {
        this.orderFor = value;
    }

    /**
     * Gets the value of the ordertype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrdertype() {
        return ordertype;
    }

    /**
     * Sets the value of the ordertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrdertype(BigInteger value) {
        this.ordertype = value;
    }

    /**
     * Gets the value of the freighttermlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreighttermlevel() {
        return freighttermlevel;
    }

    /**
     * Sets the value of the freighttermlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreighttermlevel(String value) {
        this.freighttermlevel = value;
    }

    /**
     * Gets the value of the freighttermservicelevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreighttermservicelevel() {
        return freighttermservicelevel;
    }

    /**
     * Sets the value of the freighttermservicelevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreighttermservicelevel(String value) {
        this.freighttermservicelevel = value;
    }

    /**
     * Gets the value of the parceltermlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParceltermlevel() {
        return parceltermlevel;
    }

    /**
     * Sets the value of the parceltermlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParceltermlevel(String value) {
        this.parceltermlevel = value;
    }

    /**
     * Gets the value of the parceltermservicelevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParceltermservicelevel() {
        return parceltermservicelevel;
    }

    /**
     * Sets the value of the parceltermservicelevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParceltermservicelevel(String value) {
        this.parceltermservicelevel = value;
    }

    /**
     * Gets the value of the freightaccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightaccount() {
        return freightaccount;
    }

    /**
     * Sets the value of the freightaccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightaccount(String value) {
        this.freightaccount = value;
    }

    /**
     * Gets the value of the ordertypepartnernumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdertypepartnernumber() {
        return ordertypepartnernumber;
    }

    /**
     * Sets the value of the ordertypepartnernumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdertypepartnernumber(String value) {
        this.ordertypepartnernumber = value;
    }

    /**
     * Gets the value of the shipmethodid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShipmethodid() {
        return shipmethodid;
    }

    /**
     * Sets the value of the shipmethodid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShipmethodid(BigInteger value) {
        this.shipmethodid = value;
    }

    /**
     * Gets the value of the reqdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqdate() {
        return reqdate;
    }

    /**
     * Sets the value of the reqdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqdate(String value) {
        this.reqdate = value;
    }

    /**
     * Gets the value of the pterms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPterms() {
        return pterms;
    }

    /**
     * Sets the value of the pterms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPterms(String value) {
        this.pterms = value;
    }

    /**
     * Gets the value of the fterms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFterms() {
        return fterms;
    }

    /**
     * Sets the value of the fterms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFterms(String value) {
        this.fterms = value;
    }

    /**
     * Gets the value of the prnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrnum() {
        return prnum;
    }

    /**
     * Sets the value of the prnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrnum(String value) {
        this.prnum = value;
    }

    /**
     * Gets the value of the replytotype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplytotype() {
        return replytotype;
    }

    /**
     * Sets the value of the replytotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplytotype(String value) {
        this.replytotype = value;
    }

    /**
     * Gets the value of the replyto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyto() {
        return replyto;
    }

    /**
     * Sets the value of the replyto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyto(String value) {
        this.replyto = value;
    }

    /**
     * Gets the value of the mfrid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMfrid() {
        return mfrid;
    }

    /**
     * Sets the value of the mfrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMfrid(BigInteger value) {
        this.mfrid = value;
    }

    /**
     * Gets the value of the extvendnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExtvendnum() {
        return extvendnum;
    }

    /**
     * Sets the value of the extvendnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExtvendnum(BigInteger value) {
        this.extvendnum = value;
    }

    /**
     * Gets the value of the vendorid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVendorid() {
        return vendorid;
    }

    /**
     * Sets the value of the vendorid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVendorid(BigInteger value) {
        this.vendorid = value;
    }

    /**
     * Gets the value of the cctype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCctype() {
        return cctype;
    }

    /**
     * Sets the value of the cctype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCctype(String value) {
        this.cctype = value;
    }

    /**
     * Gets the value of the ccnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcnum() {
        return ccnum;
    }

    /**
     * Sets the value of the ccnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcnum(String value) {
        this.ccnum = value;
    }

    /**
     * Gets the value of the ccname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcname() {
        return ccname;
    }

    /**
     * Sets the value of the ccname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcname(String value) {
        this.ccname = value;
    }

    /**
     * Gets the value of the ccdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcdate() {
        return ccdate;
    }

    /**
     * Sets the value of the ccdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcdate(String value) {
        this.ccdate = value;
    }

    /**
     * Gets the value of the seorderid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeorderid() {
        return seorderid;
    }

    /**
     * Sets the value of the seorderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeorderid(BigInteger value) {
        this.seorderid = value;
    }

    /**
     * Gets the value of the reasoncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasoncode() {
        return reasoncode;
    }

    /**
     * Sets the value of the reasoncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasoncode(String value) {
        this.reasoncode = value;
    }

    /**
     * Gets the value of the custdbpool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustdbpool() {
        return custdbpool;
    }

    /**
     * Sets the value of the custdbpool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustdbpool(String value) {
        this.custdbpool = value;
    }

    /**
     * Gets the value of the admindbpool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmindbpool() {
        return admindbpool;
    }

    /**
     * Sets the value of the admindbpool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmindbpool(String value) {
        this.admindbpool = value;
    }

    /**
     * Gets the value of the secustomerid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSecustomerid() {
        return secustomerid;
    }

    /**
     * Sets the value of the secustomerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSecustomerid(BigInteger value) {
        this.secustomerid = value;
    }

    /**
     * Gets the value of the locationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocationID() {
        return locationID;
    }

    /**
     * Sets the value of the locationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocationID(BigInteger value) {
        this.locationID = value;
    }

    /**
     * Gets the value of the seOrderID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeOrderID() {
        return seOrderID;
    }

    /**
     * Sets the value of the seOrderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeOrderID(BigInteger value) {
        this.seOrderID = value;
    }

    /**
     * Gets the value of the reqstoreid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqstoreid() {
        return reqstoreid;
    }

    /**
     * Sets the value of the reqstoreid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqstoreid(String value) {
        this.reqstoreid = value;
    }

    /**
     * Gets the value of the ordertypedesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdertypedesc() {
        return ordertypedesc;
    }

    /**
     * Sets the value of the ordertypedesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdertypedesc(String value) {
        this.ordertypedesc = value;
    }

    /**
     * Gets the value of the paymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTerms() {
        return paymentTerms;
    }

    /**
     * Sets the value of the paymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTerms(String value) {
        this.paymentTerms = value;
    }

}
