//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.26 at 02:35:15 PM IST 
//


package com.cxmlpunchout.sebo;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cxmlpunchout.sebo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Total_QNAME = new QName("", "total");
    private final static QName _Shipmethodid_QNAME = new QName("", "shipmethodid");
    private final static QName _Userid_QNAME = new QName("", "userid");
    private final static QName _Shipviaid_QNAME = new QName("", "shipviaid");
    private final static QName _Freighttermlevel_QNAME = new QName("", "freighttermlevel");
    private final static QName _City_QNAME = new QName("", "city");
    private final static QName _Username_QNAME = new QName("", "username");
    private final static QName _Reqtype_QNAME = new QName("", "reqtype");
    private final static QName _SeOrderID_QNAME = new QName("", "seOrderID");
    private final static QName _Distchannel_QNAME = new QName("", "distchannel");
    private final static QName _Itemnum_QNAME = new QName("", "itemnum");
    private final static QName _Curr_QNAME = new QName("", "curr");
    private final static QName _Paymentdesc_QNAME = new QName("", "paymentdesc");
    private final static QName _Shipviaacct_QNAME = new QName("", "shipviaacct");
    private final static QName _CustAcctNum_QNAME = new QName("", "custAcctNum");
    private final static QName _Seorderid_QNAME = new QName("", "seorderid");
    private final static QName _Dsphone_QNAME = new QName("", "dsphone");
    private final static QName _Shipto_QNAME = new QName("", "shipto");
    private final static QName _Statusid_QNAME = new QName("", "statusid");
    private final static QName _Shiptype_QNAME = new QName("", "shiptype");
    private final static QName _Freightaccount_QNAME = new QName("", "freightaccount");
    private final static QName _Discount_QNAME = new QName("", "discount");
    private final static QName _Replytotype_QNAME = new QName("", "replytotype");
    private final static QName _Price_QNAME = new QName("", "price");
    private final static QName _Vendorid_QNAME = new QName("", "vendorid");
    private final static QName _Bcity_QNAME = new QName("", "bcity");
    private final static QName _Po_QNAME = new QName("", "po");
    private final static QName _Freighttermservicelevel_QNAME = new QName("", "freighttermservicelevel");
    private final static QName _Comment_QNAME = new QName("", "comment");
    private final static QName _Freighttermdesc_QNAME = new QName("", "freighttermdesc");
    private final static QName _OrderFor_QNAME = new QName("", "order-for");
    private final static QName _Make_QNAME = new QName("", "Make");
    private final static QName _Plant_QNAME = new QName("", "plant");
    private final static QName _Bzip_QNAME = new QName("", "bzip");
    private final static QName _Partnum_QNAME = new QName("", "partnum");
    private final static QName _Dszip_QNAME = new QName("", "dszip");
    private final static QName _Partsrc_QNAME = new QName("", "partsrc");
    private final static QName _Dsaddr2_QNAME = new QName("", "dsaddr2");
    private final static QName _Pricomment_QNAME = new QName("", "pricomment");
    private final static QName _Confqty_QNAME = new QName("", "confqty");
    private final static QName _ModelNumber_QNAME = new QName("", "ModelNumber");
    private final static QName _Dsaddr1_QNAME = new QName("", "dsaddr1");
    private final static QName _Division_QNAME = new QName("", "division");
    private final static QName _Bstate_QNAME = new QName("", "bstate");
    private final static QName _Ccname_QNAME = new QName("", "ccname");
    private final static QName _Ccdate_QNAME = new QName("", "ccdate");
    private final static QName _Dscity_QNAME = new QName("", "dscity");
    private final static QName _Reasoncode_QNAME = new QName("", "reasoncode");
    private final static QName _Custdbpool_QNAME = new QName("", "custdbpool");
    private final static QName _Ordertypedesc_QNAME = new QName("", "ordertypedesc");
    private final static QName _Parceltermlevel_QNAME = new QName("", "parceltermlevel");
    private final static QName _Payment_QNAME = new QName("", "payment");
    private final static QName _Pterms_QNAME = new QName("", "pterms");
    private final static QName _Supplierorderid_QNAME = new QName("", "supplierorderid");
    private final static QName _Shipdate_QNAME = new QName("", "shipdate");
    private final static QName _LocationID_QNAME = new QName("", "locationID");
    private final static QName _Pricecode_QNAME = new QName("", "pricecode");
    private final static QName _Bname_QNAME = new QName("", "bname");
    private final static QName _Extvendnum_QNAME = new QName("", "extvendnum");
    private final static QName _Baddr1_QNAME = new QName("", "baddr1");
    private final static QName _Ordertypepartnernumber_QNAME = new QName("", "ordertypepartnernumber");
    private final static QName _Baddr2_QNAME = new QName("", "baddr2");
    private final static QName _Cntry_QNAME = new QName("", "cntry");
    private final static QName _Family_QNAME = new QName("", "Family");
    private final static QName _Cctype_QNAME = new QName("", "cctype");
    private final static QName _Secustomerid_QNAME = new QName("", "secustomerid");
    private final static QName _Phone_QNAME = new QName("", "phone");
    private final static QName _Confdate_QNAME = new QName("", "confdate");
    private final static QName _Replyto_QNAME = new QName("", "replyto");
    private final static QName _Fterms_QNAME = new QName("", "fterms");
    private final static QName _Password_QNAME = new QName("", "password");
    private final static QName _Dscountry_QNAME = new QName("", "dscountry");
    private final static QName _Netprice_QNAME = new QName("", "netprice");
    private final static QName _Salesorg_QNAME = new QName("", "salesorg");
    private final static QName _Bphone_QNAME = new QName("", "bphone");
    private final static QName _Distributorid_QNAME = new QName("", "distributorid");
    private final static QName _Reqstoreid_QNAME = new QName("", "reqstoreid");
    private final static QName _Prnum_QNAME = new QName("", "prnum");
    private final static QName _Qty_QNAME = new QName("", "qty");
    private final static QName _Freightterm_QNAME = new QName("", "freightterm");
    private final static QName _Ordertype_QNAME = new QName("", "ordertype");
    private final static QName _AddressID_QNAME = new QName("", "addressID");
    private final static QName _Setshipto_QNAME = new QName("", "setshipto");
    private final static QName _Addr1_QNAME = new QName("", "addr1");
    private final static QName _Addr2_QNAME = new QName("", "addr2");
    private final static QName _Email_QNAME = new QName("", "email");
    private final static QName _Doctype_QNAME = new QName("", "doctype");
    private final static QName _Prtnnum_QNAME = new QName("", "prtnnum");
    private final static QName _Ccnum_QNAME = new QName("", "ccnum");
    private final static QName _Parceltermservicelevel_QNAME = new QName("", "parceltermservicelevel");
    private final static QName _State_QNAME = new QName("", "state");
    private final static QName _Reqdate_QNAME = new QName("", "reqdate");
    private final static QName _Bcountry_QNAME = new QName("", "bcountry");
    private final static QName _Shipmethod_QNAME = new QName("", "shipmethod");
    private final static QName _Uom_QNAME = new QName("", "uom");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Dsname_QNAME = new QName("", "dsname");
    private final static QName _Shipprtnr_QNAME = new QName("", "shipprtnr");
    private final static QName _Zip_QNAME = new QName("", "zip");
    private final static QName _Dsstate_QNAME = new QName("", "dsstate");
    private final static QName _Admindbpool_QNAME = new QName("", "admindbpool");
    private final static QName _Slsoffice_QNAME = new QName("", "slsoffice");
    private final static QName _Salestype_QNAME = new QName("", "salestype");
    private final static QName _Partdesc_QNAME = new QName("", "partdesc");
    private final static QName _Mfrid_QNAME = new QName("", "mfrid");
    private final static QName _Prtnrole_QNAME = new QName("", "prtnrole");
    private final static QName _PaymentTerms_QNAME = new QName("", "paymentTerms");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cxmlpunchout.sebo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShippingAddress }
     * 
     */
    public ShippingAddress createShippingAddress() {
        return new ShippingAddress();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Partrec }
     * 
     */
    public Partrec createPartrec() {
        return new Partrec();
    }

    /**
     * Create an instance of {@link Hdrrec }
     * 
     */
    public Hdrrec createHdrrec() {
        return new Hdrrec();
    }

    /**
     * Create an instance of {@link Billingaddress }
     * 
     */
    public Billingaddress createBillingaddress() {
        return new Billingaddress();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "total")
    public JAXBElement<BigDecimal> createTotal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Total_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shipmethodid")
    public JAXBElement<BigInteger> createShipmethodid(BigInteger value) {
        return new JAXBElement<BigInteger>(_Shipmethodid_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userid")
    public JAXBElement<BigInteger> createUserid(BigInteger value) {
        return new JAXBElement<BigInteger>(_Userid_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shipviaid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShipviaid(String value) {
        return new JAXBElement<String>(_Shipviaid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "freighttermlevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFreighttermlevel(String value) {
        return new JAXBElement<String>(_Freighttermlevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "city")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "username")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUsername(String value) {
        return new JAXBElement<String>(_Username_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reqtype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReqtype(String value) {
        return new JAXBElement<String>(_Reqtype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "seOrderID")
    public JAXBElement<BigInteger> createSeOrderID(BigInteger value) {
        return new JAXBElement<BigInteger>(_SeOrderID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "distchannel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDistchannel(String value) {
        return new JAXBElement<String>(_Distchannel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "itemnum")
    public JAXBElement<BigInteger> createItemnum(BigInteger value) {
        return new JAXBElement<BigInteger>(_Itemnum_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "curr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCurr(String value) {
        return new JAXBElement<String>(_Curr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "paymentdesc")
    public JAXBElement<String> createPaymentdesc(String value) {
        return new JAXBElement<String>(_Paymentdesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shipviaacct")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShipviaacct(String value) {
        return new JAXBElement<String>(_Shipviaacct_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "custAcctNum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCustAcctNum(String value) {
        return new JAXBElement<String>(_CustAcctNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "seorderid")
    public JAXBElement<BigInteger> createSeorderid(BigInteger value) {
        return new JAXBElement<BigInteger>(_Seorderid_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dsphone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDsphone(String value) {
        return new JAXBElement<String>(_Dsphone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shipto")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShipto(String value) {
        return new JAXBElement<String>(_Shipto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "statusid")
    public JAXBElement<BigInteger> createStatusid(BigInteger value) {
        return new JAXBElement<BigInteger>(_Statusid_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shiptype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShiptype(String value) {
        return new JAXBElement<String>(_Shiptype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "freightaccount")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFreightaccount(String value) {
        return new JAXBElement<String>(_Freightaccount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "discount")
    public JAXBElement<BigDecimal> createDiscount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Discount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "replytotype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReplytotype(String value) {
        return new JAXBElement<String>(_Replytotype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "price")
    public JAXBElement<BigDecimal> createPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Price_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vendorid")
    public JAXBElement<BigInteger> createVendorid(BigInteger value) {
        return new JAXBElement<BigInteger>(_Vendorid_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bcity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBcity(String value) {
        return new JAXBElement<String>(_Bcity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "po")
    public JAXBElement<BigInteger> createPo(BigInteger value) {
        return new JAXBElement<BigInteger>(_Po_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "freighttermservicelevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFreighttermservicelevel(String value) {
        return new JAXBElement<String>(_Freighttermservicelevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "freighttermdesc")
    public JAXBElement<String> createFreighttermdesc(String value) {
        return new JAXBElement<String>(_Freighttermdesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "order-for")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOrderFor(String value) {
        return new JAXBElement<String>(_OrderFor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Make")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMake(String value) {
        return new JAXBElement<String>(_Make_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plant")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPlant(String value) {
        return new JAXBElement<String>(_Plant_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bzip")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBzip(String value) {
        return new JAXBElement<String>(_Bzip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "partnum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPartnum(String value) {
        return new JAXBElement<String>(_Partnum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dszip")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDszip(String value) {
        return new JAXBElement<String>(_Dszip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "partsrc")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPartsrc(String value) {
        return new JAXBElement<String>(_Partsrc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dsaddr2")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDsaddr2(String value) {
        return new JAXBElement<String>(_Dsaddr2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pricomment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPricomment(String value) {
        return new JAXBElement<String>(_Pricomment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "confqty")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createConfqty(String value) {
        return new JAXBElement<String>(_Confqty_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModelNumber")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createModelNumber(String value) {
        return new JAXBElement<String>(_ModelNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dsaddr1")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDsaddr1(String value) {
        return new JAXBElement<String>(_Dsaddr1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "division")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDivision(String value) {
        return new JAXBElement<String>(_Division_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bstate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBstate(String value) {
        return new JAXBElement<String>(_Bstate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ccname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCcname(String value) {
        return new JAXBElement<String>(_Ccname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ccdate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCcdate(String value) {
        return new JAXBElement<String>(_Ccdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dscity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDscity(String value) {
        return new JAXBElement<String>(_Dscity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reasoncode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReasoncode(String value) {
        return new JAXBElement<String>(_Reasoncode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "custdbpool")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCustdbpool(String value) {
        return new JAXBElement<String>(_Custdbpool_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ordertypedesc")
    public JAXBElement<String> createOrdertypedesc(String value) {
        return new JAXBElement<String>(_Ordertypedesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parceltermlevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParceltermlevel(String value) {
        return new JAXBElement<String>(_Parceltermlevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "payment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPayment(String value) {
        return new JAXBElement<String>(_Payment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pterms")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPterms(String value) {
        return new JAXBElement<String>(_Pterms_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "supplierorderid")
    public JAXBElement<String> createSupplierorderid(String value) {
        return new JAXBElement<String>(_Supplierorderid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shipdate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShipdate(String value) {
        return new JAXBElement<String>(_Shipdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "locationID")
    public JAXBElement<BigInteger> createLocationID(BigInteger value) {
        return new JAXBElement<BigInteger>(_LocationID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pricecode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPricecode(String value) {
        return new JAXBElement<String>(_Pricecode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bname")
    public JAXBElement<String> createBname(String value) {
        return new JAXBElement<String>(_Bname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extvendnum")
    public JAXBElement<BigInteger> createExtvendnum(BigInteger value) {
        return new JAXBElement<BigInteger>(_Extvendnum_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "baddr1")
    public JAXBElement<String> createBaddr1(String value) {
        return new JAXBElement<String>(_Baddr1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ordertypepartnernumber")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOrdertypepartnernumber(String value) {
        return new JAXBElement<String>(_Ordertypepartnernumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "baddr2")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBaddr2(String value) {
        return new JAXBElement<String>(_Baddr2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cntry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCntry(String value) {
        return new JAXBElement<String>(_Cntry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Family")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFamily(String value) {
        return new JAXBElement<String>(_Family_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cctype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCctype(String value) {
        return new JAXBElement<String>(_Cctype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "secustomerid")
    public JAXBElement<BigInteger> createSecustomerid(BigInteger value) {
        return new JAXBElement<BigInteger>(_Secustomerid_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPhone(String value) {
        return new JAXBElement<String>(_Phone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "confdate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createConfdate(String value) {
        return new JAXBElement<String>(_Confdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "replyto")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReplyto(String value) {
        return new JAXBElement<String>(_Replyto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fterms")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFterms(String value) {
        return new JAXBElement<String>(_Fterms_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "password")
    public JAXBElement<String> createPassword(String value) {
        return new JAXBElement<String>(_Password_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dscountry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDscountry(String value) {
        return new JAXBElement<String>(_Dscountry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "netprice")
    public JAXBElement<BigDecimal> createNetprice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Netprice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "salesorg")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSalesorg(String value) {
        return new JAXBElement<String>(_Salesorg_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bphone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBphone(String value) {
        return new JAXBElement<String>(_Bphone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "distributorid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDistributorid(String value) {
        return new JAXBElement<String>(_Distributorid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reqstoreid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReqstoreid(String value) {
        return new JAXBElement<String>(_Reqstoreid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "prnum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrnum(String value) {
        return new JAXBElement<String>(_Prnum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "qty")
    public JAXBElement<BigInteger> createQty(BigInteger value) {
        return new JAXBElement<BigInteger>(_Qty_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "freightterm")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFreightterm(String value) {
        return new JAXBElement<String>(_Freightterm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ordertype")
    public JAXBElement<BigInteger> createOrdertype(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ordertype_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addressID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAddressID(String value) {
        return new JAXBElement<String>(_AddressID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "setshipto")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSetshipto(String value) {
        return new JAXBElement<String>(_Setshipto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addr1")
    public JAXBElement<String> createAddr1(String value) {
        return new JAXBElement<String>(_Addr1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addr2")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAddr2(String value) {
        return new JAXBElement<String>(_Addr2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "doctype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDoctype(String value) {
        return new JAXBElement<String>(_Doctype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "prtnnum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrtnnum(String value) {
        return new JAXBElement<String>(_Prtnnum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ccnum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCcnum(String value) {
        return new JAXBElement<String>(_Ccnum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parceltermservicelevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParceltermservicelevel(String value) {
        return new JAXBElement<String>(_Parceltermservicelevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "state")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reqdate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReqdate(String value) {
        return new JAXBElement<String>(_Reqdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bcountry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBcountry(String value) {
        return new JAXBElement<String>(_Bcountry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shipmethod")
    public JAXBElement<String> createShipmethod(String value) {
        return new JAXBElement<String>(_Shipmethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uom")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUom(String value) {
        return new JAXBElement<String>(_Uom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dsname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDsname(String value) {
        return new JAXBElement<String>(_Dsname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shipprtnr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShipprtnr(String value) {
        return new JAXBElement<String>(_Shipprtnr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zip")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createZip(String value) {
        return new JAXBElement<String>(_Zip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dsstate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDsstate(String value) {
        return new JAXBElement<String>(_Dsstate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "admindbpool")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAdmindbpool(String value) {
        return new JAXBElement<String>(_Admindbpool_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "slsoffice")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSlsoffice(String value) {
        return new JAXBElement<String>(_Slsoffice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "salestype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSalestype(String value) {
        return new JAXBElement<String>(_Salestype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "partdesc")
    public JAXBElement<String> createPartdesc(String value) {
        return new JAXBElement<String>(_Partdesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mfrid")
    public JAXBElement<BigInteger> createMfrid(BigInteger value) {
        return new JAXBElement<BigInteger>(_Mfrid_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "prtnrole")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrtnrole(String value) {
        return new JAXBElement<String>(_Prtnrole_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "paymentTerms")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPaymentTerms(String value) {
        return new JAXBElement<String>(_PaymentTerms_QNAME, String.class, null, value);
    }

}
