//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.26 at 02:35:15 PM IST 
//


package com.cxmlpunchout.sebo;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}itemnum"/>
 *         &lt;element ref="{}plant"/>
 *         &lt;element ref="{}partnum"/>
 *         &lt;element ref="{}qty"/>
 *         &lt;element ref="{}confqty"/>
 *         &lt;element ref="{}confdate"/>
 *         &lt;element ref="{}uom"/>
 *         &lt;element ref="{}price"/>
 *         &lt;element ref="{}netprice"/>
 *         &lt;element ref="{}discount"/>
 *         &lt;element ref="{}pricomment"/>
 *         &lt;element ref="{}distributorid"/>
 *         &lt;element ref="{}partdesc"/>
 *         &lt;element ref="{}partsrc"/>
 *         &lt;element ref="{}shipdate"/>
 *         &lt;element ref="{}shipmethod"/>
 *         &lt;element ref="{}fterms"/>
 *         &lt;element ref="{}ModelNumber"/>
 *         &lt;element ref="{}Make"/>
 *         &lt;element ref="{}Family"/>
 *         &lt;element ref="{}supplierorderid"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemnum",
    "plant",
    "partnum",
    "qty",
    "confqty",
    "confdate",
    "uom",
    "price",
    "netprice",
    "discount",
    "pricomment",
    "distributorid",
    "partdesc",
    "partsrc",
    "shipdate",
    "shipmethod",
    "fterms",
    "modelNumber",
    "make",
    "family",
    "supplierorderid"
})
@XmlRootElement(name = "partrec")
public class Partrec {

    @XmlElement(required = true)
    protected BigInteger itemnum;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String plant;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String partnum;
    @XmlElement(required = true)
    protected BigInteger qty;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String confqty;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String confdate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uom;
    @XmlElement(required = true)
    protected BigDecimal price;
    @XmlElement(required = true)
    protected BigDecimal netprice;
    @XmlElement(required = true)
    protected BigDecimal discount;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pricomment;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String distributorid;
    @XmlElement(required = true)
    protected String partdesc;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String partsrc;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String shipdate;
    @XmlElement(required = true)
    protected String shipmethod;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fterms;
    @XmlElement(name = "ModelNumber", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String modelNumber;
    @XmlElement(name = "Make", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String make;
    @XmlElement(name = "Family", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String family;
    @XmlElement(required = true)
    protected String supplierorderid;

    /**
     * Gets the value of the itemnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getItemnum() {
        return itemnum;
    }

    /**
     * Sets the value of the itemnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setItemnum(BigInteger value) {
        this.itemnum = value;
    }

    /**
     * Gets the value of the plant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlant() {
        return plant;
    }

    /**
     * Sets the value of the plant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlant(String value) {
        this.plant = value;
    }

    /**
     * Gets the value of the partnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnum() {
        return partnum;
    }

    /**
     * Sets the value of the partnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnum(String value) {
        this.partnum = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQty(BigInteger value) {
        this.qty = value;
    }

    /**
     * Gets the value of the confqty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfqty() {
        return confqty;
    }

    /**
     * Sets the value of the confqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfqty(String value) {
        this.confqty = value;
    }

    /**
     * Gets the value of the confdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfdate() {
        return confdate;
    }

    /**
     * Sets the value of the confdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfdate(String value) {
        this.confdate = value;
    }

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUom() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUom(String value) {
        this.uom = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the netprice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetprice() {
        return netprice;
    }

    /**
     * Sets the value of the netprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetprice(BigDecimal value) {
        this.netprice = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscount(BigDecimal value) {
        this.discount = value;
    }

    /**
     * Gets the value of the pricomment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricomment() {
        return pricomment;
    }

    /**
     * Sets the value of the pricomment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricomment(String value) {
        this.pricomment = value;
    }

    /**
     * Gets the value of the distributorid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributorid() {
        return distributorid;
    }

    /**
     * Sets the value of the distributorid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributorid(String value) {
        this.distributorid = value;
    }

    /**
     * Gets the value of the partdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartdesc() {
        return partdesc;
    }

    /**
     * Sets the value of the partdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartdesc(String value) {
        this.partdesc = value;
    }

    /**
     * Gets the value of the partsrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartsrc() {
        return partsrc;
    }

    /**
     * Sets the value of the partsrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartsrc(String value) {
        this.partsrc = value;
    }

    /**
     * Gets the value of the shipdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipdate() {
        return shipdate;
    }

    /**
     * Sets the value of the shipdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipdate(String value) {
        this.shipdate = value;
    }

    /**
     * Gets the value of the shipmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmethod() {
        return shipmethod;
    }

    /**
     * Sets the value of the shipmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmethod(String value) {
        this.shipmethod = value;
    }

    /**
     * Gets the value of the fterms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFterms() {
        return fterms;
    }

    /**
     * Sets the value of the fterms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFterms(String value) {
        this.fterms = value;
    }

    /**
     * Gets the value of the modelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * Sets the value of the modelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelNumber(String value) {
        this.modelNumber = value;
    }

    /**
     * Gets the value of the make property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMake() {
        return make;
    }

    /**
     * Sets the value of the make property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMake(String value) {
        this.make = value;
    }

    /**
     * Gets the value of the family property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamily() {
        return family;
    }

    /**
     * Sets the value of the family property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamily(String value) {
        this.family = value;
    }

    /**
     * Gets the value of the supplierorderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierorderid() {
        return supplierorderid;
    }

    /**
     * Sets the value of the supplierorderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierorderid(String value) {
        this.supplierorderid = value;
    }

}
