//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.18 at 05:46:33 PM IST 
//


package com.cxmlpunchout.sebo.cxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}TravelDetail"/>
 *         &lt;element ref="{}FeeDetail"/>
 *         &lt;element ref="{}LaborDetail"/>
 *         &lt;element ref="{}Extrinsic"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "travelDetail",
    "feeDetail",
    "laborDetail",
    "extrinsic"
})
@XmlRootElement(name = "SpendDetail")
public class SpendDetail {

    @XmlElement(name = "TravelDetail")
    protected TravelDetail travelDetail;
    @XmlElement(name = "FeeDetail")
    protected FeeDetail feeDetail;
    @XmlElement(name = "LaborDetail")
    protected LaborDetail laborDetail;
    @XmlElement(name = "Extrinsic")
    protected Extrinsic extrinsic;

    /**
     * Gets the value of the travelDetail property.
     * 
     * @return
     *     possible object is
     *     {@link TravelDetail }
     *     
     */
    public TravelDetail getTravelDetail() {
        return travelDetail;
    }

    /**
     * Sets the value of the travelDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TravelDetail }
     *     
     */
    public void setTravelDetail(TravelDetail value) {
        this.travelDetail = value;
    }

    /**
     * Gets the value of the feeDetail property.
     * 
     * @return
     *     possible object is
     *     {@link FeeDetail }
     *     
     */
    public FeeDetail getFeeDetail() {
        return feeDetail;
    }

    /**
     * Sets the value of the feeDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeeDetail }
     *     
     */
    public void setFeeDetail(FeeDetail value) {
        this.feeDetail = value;
    }

    /**
     * Gets the value of the laborDetail property.
     * 
     * @return
     *     possible object is
     *     {@link LaborDetail }
     *     
     */
    public LaborDetail getLaborDetail() {
        return laborDetail;
    }

    /**
     * Sets the value of the laborDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaborDetail }
     *     
     */
    public void setLaborDetail(LaborDetail value) {
        this.laborDetail = value;
    }

    /**
     * Gets the value of the extrinsic property.
     * 
     * @return
     *     possible object is
     *     {@link Extrinsic }
     *     
     */
    public Extrinsic getExtrinsic() {
        return extrinsic;
    }

    /**
     * Sets the value of the extrinsic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extrinsic }
     *     
     */
    public void setExtrinsic(Extrinsic value) {
        this.extrinsic = value;
    }

}
