//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.18 at 05:46:33 PM IST 
//


package com.cxmlpunchout.sebo.cxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}CounterSignature"/>
 *         &lt;element ref="{}SignatureTimeStamp"/>
 *         &lt;element ref="{}CompleteCertificateRefs"/>
 *         &lt;element ref="{}CompleteRevocationRefs"/>
 *         &lt;element ref="{}AttributeCertificateRefs"/>
 *         &lt;element ref="{}AttributeRevocationRefs"/>
 *         &lt;choice>
 *           &lt;element ref="{}SigAndRefsTimeStamp"/>
 *           &lt;element ref="{}RefsOnlyTimeStamp"/>
 *         &lt;/choice>
 *         &lt;element ref="{}CertificateValues"/>
 *         &lt;element ref="{}RevocationValues"/>
 *         &lt;element ref="{}AttrAuthoritiesCertValues"/>
 *         &lt;element ref="{}AttributeRevocationValues"/>
 *         &lt;element ref="{}ArchiveTimeStamp"/>
 *       &lt;/choice>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs"
})
@XmlRootElement(name = "UnsignedSignatureProperties")
public class UnsignedSignatureProperties {

    @XmlElements({
        @XmlElement(name = "ArchiveTimeStamp", type = ArchiveTimeStamp.class),
        @XmlElement(name = "CompleteCertificateRefs", type = CompleteCertificateRefs.class),
        @XmlElement(name = "CompleteRevocationRefs", type = CompleteRevocationRefs.class),
        @XmlElement(name = "SigAndRefsTimeStamp", type = SigAndRefsTimeStamp.class),
        @XmlElement(name = "AttributeCertificateRefs", type = AttributeCertificateRefs.class),
        @XmlElement(name = "CounterSignature", type = CounterSignature.class),
        @XmlElement(name = "SignatureTimeStamp", type = SignatureTimeStamp.class),
        @XmlElement(name = "CertificateValues", type = CertificateValues.class),
        @XmlElement(name = "RevocationValues", type = RevocationValues.class),
        @XmlElement(name = "RefsOnlyTimeStamp", type = RefsOnlyTimeStamp.class),
        @XmlElement(name = "AttributeRevocationRefs", type = AttributeRevocationRefs.class),
        @XmlElement(name = "AttrAuthoritiesCertValues", type = AttrAuthoritiesCertValues.class),
        @XmlElement(name = "AttributeRevocationValues", type = AttributeRevocationValues.class)
    })
    protected List<java.lang.Object> counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCounterSignatureOrSignatureTimeStampOrCompleteCertificateRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArchiveTimeStamp }
     * {@link CompleteCertificateRefs }
     * {@link CompleteRevocationRefs }
     * {@link SigAndRefsTimeStamp }
     * {@link AttributeCertificateRefs }
     * {@link CounterSignature }
     * {@link SignatureTimeStamp }
     * {@link CertificateValues }
     * {@link RevocationValues }
     * {@link RefsOnlyTimeStamp }
     * {@link AttributeRevocationRefs }
     * {@link AttrAuthoritiesCertValues }
     * {@link AttributeRevocationValues }
     * 
     * 
     */
    public List<java.lang.Object> getCounterSignatureOrSignatureTimeStampOrCompleteCertificateRefs() {
        if (counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs == null) {
            counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs = new ArrayList<java.lang.Object>();
        }
        return this.counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
