//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.26 at 02:35:15 PM IST 
//


package com.cxmlpunchout.sebo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}bname"/>
 *         &lt;element ref="{}baddr1"/>
 *         &lt;element ref="{}baddr2"/>
 *         &lt;element ref="{}bcity"/>
 *         &lt;element ref="{}bstate"/>
 *         &lt;element ref="{}bzip"/>
 *         &lt;element ref="{}bphone"/>
 *         &lt;element ref="{}bcountry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bname",
    "baddr1",
    "baddr2",
    "bcity",
    "bstate",
    "bzip",
    "bphone",
    "bcountry"
})
@XmlRootElement(name = "billingaddress")
public class Billingaddress {

    @XmlElement(required = true)
    protected String bname;
    @XmlElement(required = true)
    protected String baddr1;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String baddr2;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bcity;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bstate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bzip;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bphone;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bcountry;

    /**
     * Gets the value of the bname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBname() {
        return bname;
    }

    /**
     * Sets the value of the bname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBname(String value) {
        this.bname = value;
    }

    /**
     * Gets the value of the baddr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaddr1() {
        return baddr1;
    }

    /**
     * Sets the value of the baddr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaddr1(String value) {
        this.baddr1 = value;
    }

    /**
     * Gets the value of the baddr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaddr2() {
        return baddr2;
    }

    /**
     * Sets the value of the baddr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaddr2(String value) {
        this.baddr2 = value;
    }

    /**
     * Gets the value of the bcity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBcity() {
        return bcity;
    }

    /**
     * Sets the value of the bcity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBcity(String value) {
        this.bcity = value;
    }

    /**
     * Gets the value of the bstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBstate() {
        return bstate;
    }

    /**
     * Sets the value of the bstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBstate(String value) {
        this.bstate = value;
    }

    /**
     * Gets the value of the bzip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBzip() {
        return bzip;
    }

    /**
     * Sets the value of the bzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBzip(String value) {
        this.bzip = value;
    }

    /**
     * Gets the value of the bphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBphone() {
        return bphone;
    }

    /**
     * Sets the value of the bphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBphone(String value) {
        this.bphone = value;
    }

    /**
     * Gets the value of the bcountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBcountry() {
        return bcountry;
    }

    /**
     * Sets the value of the bcountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBcountry(String value) {
        this.bcountry = value;
    }

}
