//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.26 at 02:35:15 PM IST 
//


package com.cxmlpunchout.sebo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}reqtype"/>
 *         &lt;element ref="{}hdrrec"/>
 *         &lt;element ref="{}shippingAddress"/>
 *         &lt;element ref="{}dsname"/>
 *         &lt;element ref="{}dsaddr1"/>
 *         &lt;element ref="{}dsaddr2"/>
 *         &lt;element ref="{}dscity"/>
 *         &lt;element ref="{}dsstate"/>
 *         &lt;element ref="{}dszip"/>
 *         &lt;element ref="{}dsphone"/>
 *         &lt;element ref="{}dscountry"/>
 *         &lt;element ref="{}billingaddress"/>
 *         &lt;element ref="{}partrec" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reqtype",
    "hdrrec",
    "shippingAddress",
    "dsname",
    "dsaddr1",
    "dsaddr2",
    "dscity",
    "dsstate",
    "dszip",
    "dsphone",
    "dscountry",
    "billingaddress",
    "partrec"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String reqtype;
    @XmlElement(required = true)
    protected Hdrrec hdrrec;
    @XmlElement(required = true)
    protected ShippingAddress shippingAddress;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dsname;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dsaddr1;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dsaddr2;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dscity;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dsstate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dszip;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dsphone;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dscountry;
    @XmlElement(required = true)
    protected Billingaddress billingaddress;
    @XmlElement(required = true)
    protected List<Partrec> partrec;

    /**
     * Gets the value of the reqtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqtype() {
        return reqtype;
    }

    /**
     * Sets the value of the reqtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqtype(String value) {
        this.reqtype = value;
    }

    /**
     * Gets the value of the hdrrec property.
     * 
     * @return
     *     possible object is
     *     {@link Hdrrec }
     *     
     */
    public Hdrrec getHdrrec() {
        return hdrrec;
    }

    /**
     * Sets the value of the hdrrec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hdrrec }
     *     
     */
    public void setHdrrec(Hdrrec value) {
        this.hdrrec = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingAddress }
     *     
     */
    public ShippingAddress getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingAddress }
     *     
     */
    public void setShippingAddress(ShippingAddress value) {
        this.shippingAddress = value;
    }

    /**
     * Gets the value of the dsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsname() {
        return dsname;
    }

    /**
     * Sets the value of the dsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsname(String value) {
        this.dsname = value;
    }

    /**
     * Gets the value of the dsaddr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsaddr1() {
        return dsaddr1;
    }

    /**
     * Sets the value of the dsaddr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsaddr1(String value) {
        this.dsaddr1 = value;
    }

    /**
     * Gets the value of the dsaddr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsaddr2() {
        return dsaddr2;
    }

    /**
     * Sets the value of the dsaddr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsaddr2(String value) {
        this.dsaddr2 = value;
    }

    /**
     * Gets the value of the dscity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDscity() {
        return dscity;
    }

    /**
     * Sets the value of the dscity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDscity(String value) {
        this.dscity = value;
    }

    /**
     * Gets the value of the dsstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsstate() {
        return dsstate;
    }

    /**
     * Sets the value of the dsstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsstate(String value) {
        this.dsstate = value;
    }

    /**
     * Gets the value of the dszip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDszip() {
        return dszip;
    }

    /**
     * Sets the value of the dszip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDszip(String value) {
        this.dszip = value;
    }

    /**
     * Gets the value of the dsphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsphone() {
        return dsphone;
    }

    /**
     * Sets the value of the dsphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsphone(String value) {
        this.dsphone = value;
    }

    /**
     * Gets the value of the dscountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDscountry() {
        return dscountry;
    }

    /**
     * Sets the value of the dscountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDscountry(String value) {
        this.dscountry = value;
    }

    /**
     * Gets the value of the billingaddress property.
     * 
     * @return
     *     possible object is
     *     {@link Billingaddress }
     *     
     */
    public Billingaddress getBillingaddress() {
        return billingaddress;
    }

    /**
     * Sets the value of the billingaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Billingaddress }
     *     
     */
    public void setBillingaddress(Billingaddress value) {
        this.billingaddress = value;
    }

    /**
     * Gets the value of the partrec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partrec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartrec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Partrec }
     * 
     * 
     */
    public List<Partrec> getPartrec() {
        if (partrec == null) {
            partrec = new ArrayList<Partrec>();
        }
        return this.partrec;
    }

}
